# Generated by Django 3.1.3 on 2020-11-12 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0003_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityAdress',
            fields=[
                ('ca_id', models.AutoField(primary_key=True, serialize=False)),
                ('ca_adress', models.CharField(max_length=150)),
                ('ca_stores', models.IntegerField(default=0)),
                ('ca_latitude', models.FloatField()),
                ('ca_longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DepartamentAdress',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfp_dapp.cityadress')),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
