# Generated by Django 3.1.3 on 2020-11-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0005_auto_20201112_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamentadress',
            name='dep_latitude',
        ),
        migrations.RemoveField(
            model_name='departamentadress',
            name='dep_longitude',
        ),
    ]
