# Generated by Django 3.1.3 on 2020-11-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0007_auto_20201112_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityadress',
            name='ca_stores',
            field=models.IntegerField(verbose_name='Кількість поверхів'),
        ),
    ]
