# Generated by Django 3.1.3 on 2020-11-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0009_auto_20201113_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityadress',
            name='ca_latitude',
            field=models.CharField(max_length=30, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='cityadress',
            name='ca_longitude',
            field=models.CharField(max_length=30, verbose_name='Довгота'),
        ),
        migrations.AlterField(
            model_name='cityadress',
            name='ca_stores',
            field=models.CharField(max_length=2, verbose_name='Кількість поверхів'),
        ),
    ]
