# Generated by Django 3.1.3 on 2020-11-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0010_auto_20201116_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamentadress',
            name='dep_big_ladder',
            field=models.CharField(default=1, max_length=2, verbose_name='з драбиною, до 10-ти поверхів'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamentadress',
            name='dep_chemical',
            field=models.CharField(default=1, max_length=2, verbose_name='з хімічними засобами пожежогасіння'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamentadress',
            name='dep_latitude',
            field=models.CharField(default=1, max_length=30, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamentadress',
            name='dep_longitude',
            field=models.CharField(default=1, max_length=30, verbose_name='Довгота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamentadress',
            name='dep_rapid',
            field=models.CharField(default=1, max_length=2, verbose_name='Кількість автомобілів:\n- швидкого реагування'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamentadress',
            name='dep_small_ladder',
            field=models.CharField(default=1, max_length=2, verbose_name='- з драбиною, до 5-ти поверхів'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamentadress',
            name='depa_big_tank',
            field=models.CharField(default=1, max_length=2, verbose_name='- з великою ємністю'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departamentadress',
            name='dep_adress',
            field=models.CharField(max_length=150, verbose_name='Адреса'),
        ),
    ]
