# Generated by Django 3.1.3 on 2020-11-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0011_auto_20201116_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentadress',
            name='dep_big_ladder',
            field=models.CharField(max_length=2, verbose_name='- з драбиною, до 10-ти поверхів'),
        ),
        migrations.AlterField(
            model_name='departamentadress',
            name='dep_chemical',
            field=models.CharField(max_length=2, verbose_name='- з хімічними засобами пожежогасіння'),
        ),
        migrations.AlterField(
            model_name='departamentadress',
            name='dep_rapid',
            field=models.CharField(max_length=2, verbose_name='_____ АВТОМОБІЛІВ _____:\n- швидкого реагування'),
        ),
    ]
