# Generated by Django 3.1.3 on 2020-11-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0012_auto_20201116_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamentadress',
            old_name='depa_big_tank',
            new_name='dep_big_tank',
        ),
    ]
