# Generated by Django 3.1.3 on 2020-11-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0013_auto_20201116_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('em_adress', models.CharField(max_length=150, verbose_name='Адреса')),
                ('em_type', models.CharField(choices=[(1, 'Пожежа у будинку'), (2, 'Пожежа у ДТП'), (3, 'Пожежа на підприємстві'), (4, 'Пожежа за наявності химічних речовин')], default=1, max_length=1)),
                ('em_date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
