# Generated by Django 3.1.3 on 2020-11-20 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0014_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='em_time_created',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emergency',
            name='em_type',
            field=models.CharField(choices=[('Пожежа у будинку', 'Пожежа у будинку'), ('Пожежа у ДТП', 'Пожежа у ДТП'), ('Пожежа на підприємстві', 'Пожежа на підприємстві'), ('Пожежа за наявності химічних речовин', 'Пожежа за наявності химічних речовин')], default='Пожежа у будинку', max_length=40),
        ),
    ]
