# Generated by Django 3.1.3 on 2020-11-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0016_emergency_em_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergencye',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('em_adress', models.CharField(max_length=150, verbose_name='Адреса')),
                ('em_type', models.CharField(choices=[('Пожежа у будинку', 'Пожежа у будинку'), ('Пожежа у ДТП', 'Пожежа у ДТП'), ('Пожежа на підприємстві', 'Пожежа на підприємстві'), ('Пожежа за наявності химічних речовин', 'Пожежа за наявності химічних речовин')], default='Пожежа у будинку', max_length=40, verbose_name='Тип ЧС')),
                ('em_date_created', models.DateField(auto_now_add=True)),
                ('em_time_created', models.TimeField(auto_now_add=True)),
                ('em_activated', models.BooleanField(default=True, verbose_name='Виконується зараз.')),
            ],
        ),
        migrations.RenameModel(
            old_name='CityAdress',
            new_name='CityAdresse',
        ),
        migrations.RenameModel(
            old_name='DepartamentAdress',
            new_name='DepartamentAdresse',
        ),
        migrations.DeleteModel(
            name='Emergency',
        ),
    ]
