# Generated by Django 3.1.3 on 2020-11-20 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0017_auto_20201120_1323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CityAdresse',
            new_name='CityAdress',
        ),
        migrations.RenameModel(
            old_name='DepartamentAdresse',
            new_name='DepartamentAdress',
        ),
        migrations.RenameModel(
            old_name='Emergencye',
            new_name='Emergency',
        ),
    ]
