# Generated by Django 3.1.3 on 2020-11-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0018_auto_20201120_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='em_type',
            field=models.CharField(choices=[('Пожежа у будинку', 'Пожежа у будинку'), ('Пожежа підчас ДТП', 'Пожежа підчас ДТП'), ('Пожежа на підприємстві', 'Пожежа на підприємстві'), ('Пожежа за наявності химічних речовин', 'Пожежа за наявності химічних речовин')], default='Пожежа у будинку', max_length=40, verbose_name='Тип ЧС'),
        ),
    ]
