# Generated by Django 3.1.3 on 2020-11-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0019_auto_20201121_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='em_list_resource',
            field=models.CharField(default='00000', editable=False, max_length=5),
        ),
    ]
