# Generated by Django 3.1.3 on 2020-11-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0020_emergency_em_list_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergency',
            old_name='em_list_resource',
            new_name='em_list_resources',
        ),
    ]
