# Generated by Django 3.1.3 on 2020-11-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0022_auto_20201121_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='em_dep_id',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
