# Generated by Django 3.1.3 on 2020-11-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0023_emergency_em_dep_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityadress',
            name='ca_house_number',
        ),
        migrations.RemoveField(
            model_name='departamentadress',
            name='dep_house_number',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='em_dep_id',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='em_house_number',
        ),
    ]
