# Generated by Django 3.1.3 on 2020-11-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0024_auto_20201123_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ca_address', models.CharField(max_length=150, verbose_name='Адреса')),
                ('ca_house_number', models.CharField(max_length=150, verbose_name='Номер будинку')),
                ('ca_stores', models.CharField(max_length=2, verbose_name='Кількість поверхів')),
                ('ca_latitude', models.CharField(max_length=30, verbose_name='Широта')),
                ('ca_longitude', models.CharField(max_length=30, verbose_name='Довгота')),
            ],
        ),
        migrations.CreateModel(
            name='DepartamentAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_address', models.CharField(max_length=150, verbose_name='Адреса')),
                ('dep_house_number', models.CharField(max_length=150, verbose_name='Номер будинку')),
                ('dep_latitude', models.CharField(max_length=30, verbose_name='Широта')),
                ('dep_longitude', models.CharField(max_length=30, verbose_name='Довгота')),
                ('dep_rapid', models.CharField(max_length=2, verbose_name='_____ АВТОМОБІЛІВ _____:\n- швидкого реагування')),
                ('dep_big_tank', models.CharField(max_length=2, verbose_name='- з великою ємністю')),
                ('dep_small_ladder', models.CharField(max_length=2, verbose_name='- з драбиною, до 5-ти поверхів')),
                ('dep_big_ladder', models.CharField(max_length=2, verbose_name='- з драбиною, до 10-ти поверхів')),
                ('dep_chemical', models.CharField(max_length=2, verbose_name='- з хімічними засобами пожежогасіння')),
            ],
        ),
        migrations.DeleteModel(
            name='CityAdress',
        ),
        migrations.DeleteModel(
            name='DepartamentAdress',
        ),
        migrations.RenameField(
            model_name='emergency',
            old_name='em_adress',
            new_name='em_address',
        ),
        migrations.AddField(
            model_name='emergency',
            name='em_house_number',
            field=models.CharField(default=None, max_length=150, verbose_name='Номер будинку'),
            preserve_default=False,
        ),
    ]
