# Generated by Django 3.1.3 on 2020-11-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0025_auto_20201124_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='em_dep_resources',
            field=models.CharField(default='No departament', editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='em_list_resources',
            field=models.CharField(default='00000', editable=False, max_length=7),
        ),
    ]
