# Generated by Django 3.1.3 on 2020-12-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0026_auto_20201126_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='em_activated',
            field=models.BooleanField(default=True, editable=False, verbose_name='Виконується зараз.'),
        ),
    ]
