# Generated by Django 3.1.3 on 2020-12-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0028_auto_20201205_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamentaddress',
            name='map_frame',
        ),
    ]
