# Generated by Django 3.1.3 on 2020-12-06 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0029_remove_departamentaddress_map_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='em_address',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, max_length=150, on_delete=django.db.models.deletion.CASCADE, to='pfp_dapp.cityaddress', verbose_name='Адреса'),
        ),
    ]
