# Generated by Django 3.1.3 on 2020-12-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0031_auto_20201206_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='em_address',
            field=models.CharField(max_length=150, verbose_name='Адреса'),
        ),
    ]
