# Generated by Django 3.1.3 on 2020-12-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0033_auto_20201206_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='em_latitude',
            field=models.CharField(default='', max_length=30, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergency',
            name='em_longitude',
            field=models.CharField(default='', max_length=30, verbose_name='Довгота'),
            preserve_default=False,
        ),
    ]
