# Generated by Django 3.1.3 on 2020-12-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0034_auto_20201206_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='ea_stores',
            field=models.CharField(default=1, max_length=2, verbose_name='Кількість поверхів'),
            preserve_default=False,
        ),
    ]
