# Generated by Django 3.1.3 on 2020-12-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfp_dapp', '0035_emergency_ea_stores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergency',
            old_name='ea_stores',
            new_name='em_stores',
        ),
    ]
